In [3]:
import numpy as np           # 提供维度数组与矩阵运算
import copy                  # 从copy模块导入深度拷贝方法
from board import Chessboard
import itertools

# 基于棋盘类，设计搜索策略
class Game:
    def __init__(self, show = True):
        """
        初始化游戏状态.
        """
        
        self.chessBoard = Chessboard(show)
        self.solves = []
        self.gameInit()
        
    # 重置游戏
    def gameInit(self, show = True):
        """
        重置棋盘.
        """
        
        self.Queen_setRow = [-1] * 8
        self.chessBoard.boardInit(False)
        
    ##############################################################################
    ####                请在以下区域中作答(可自由添加自定义函数)                 #### 
    ####              输出：self.solves = 八皇后所有序列解的list                ####
    ####             如:[[0,6,4,7,1,3,5,2],]代表八皇后的一个解为                ####
    ####           (0,0),(1,6),(2,4),(3,7),(4,1),(5,3),(6,5),(7,2)            ####
    ##############################################################################
    #                                                                            #
    
    def run(self, row=0):
        base = [num for num in range(8)]
        base_list = list(itertools.permutations(base, 8))
        for solution in base_list:
            self.Queen_setRow = list(solution)
            for i,item in enumerate(self.Queen_setRow):
                if (self.chessBoard.setLegal(i, item)):
                    self.chessBoard.setQueen(i, item, False)
                    if (i == 7 and self.chessBoard.isWin()):
                        self.solves.append(self.Queen_setRow)
                else:
                    continue
            self.Queen_setRow = [-1] * 8
            self.chessBoard.boardInit(False)
        # self.solves.append([0,6,4,7,1,3,5,2])

    #                                                                            #
    ##############################################################################
    #################             完成后请记得提交作业             ################# 
    ##############################################################################
    
    def showResults(self, result):
        """
        结果展示.
        """
        
        self.chessBoard.boardInit(False)
        for i,item in enumerate(result):
            if item >= 0:
                self.chessBoard.setQueen(i,item,False)
        
        self.chessBoard.printChessboard(False)
    
    def get_results(self):
        """
        输出结果(请勿修改此函数).
        return: 八皇后的序列解的list.
        """
        
        self.run()
        return self.solves
   

In [4]:
game = Game()
solutions = game.get_results()
print('There are {} results.'.format(len(solutions)))
game.showResults(solutions[0])

  0 1 2 3 4 5 6 7 
0 - - - - - - - - 
1 - - - - - - - - 
2 - - - - - - - - 
3 - - - - - - - - 
4 - - - - - - - - 
5 - - - - - - - - 
6 - - - - - - - - 
7 - - - - - - - - 
There are 92 results.
  0 1 2 3 4 5 6 7 
0 o - - - - - - - 
1 - - - - o - - - 
2 - - - - - - - o 
3 - - - - - o - - 
4 - - o - - - - - 
5 - - - - - - o - 
6 - o - - - - - - 
7 - - - o - - - - 


In [4]:
from board import Chessboard
chessboard = Chessboard(False)
chessboard.boardInit(False)
print(chessboard.chessboardMatrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
